export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function ProductSsrLayout(
    {
        children,
    }: {
        children: React.ReactNode
    }) {
    return (
        <>
            {children}
        </>
    )
}
